# Generated by Django 3.2 on 2021-08-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210811_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='shippingadress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.JSONField(null=True),
        ),
    ]
